# Generated by Django 4.1.7 on 2025-04-30 11:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sciencefiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('continue_watching', 'Continue Watching'), ('popular', 'Popular on Netfilm'), ('trending', 'Trending Now'), ('new_releases', 'New Releases')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('movies', models.ManyToManyField(related_name='sections', to='core.movie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
